import os
import json
from datetime import datetime

REPORT_DIR = "reports"
os.makedirs(REPORT_DIR, exist_ok=True)

class HIPGenerator:
    @staticmethod
    def generate_report(session_data, persona_detected, risk_score):
        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        report_id = f"HIP_{timestamp}_{session_data.get('client_ip', 'unknown')}"
        
        md_content = f"""# 🕵️ Hacker Intelligence Package (HIP)
**Report ID:** {report_id}
**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Confidentiality Level:** RED

## 1. Executive Summary
**Attacker IP:** `{session_data.get('client_ip')}`
**Detected Persona:** **{persona_detected.upper()}**
**Risk Score:** {risk_score}/100
**Status:** MITIGATED via Deception Engine

## 2. Behavioral Analysis
The system analyzed {session_data.get('req_count', 0)} requests from this source.
- **Burst Rate:** {session_data.get('burst_rate', 0):.2f} (High burst indicates automation)
- **IDOR Index:** {session_data.get('idor_seq_score', 0):.2f} (Sequential access attempt)
- **Unique Paths:** {session_data.get('unique_paths', 0)}

## 3. Deception Applied
Based on the classification of `{persona_detected}`, the following active defense was deployed:
- Strategy: **{HIPGenerator.get_strategy_name(persona_detected)}**
- Outcome: Attacker diverted/delayed.

## 4. Recommendations
1. Block IP `{session_data.get('client_ip')}` on edge firewall.
2. Rotate credentials if `admin` endpoint was touched.
3. Investigate similar IPs from subnet.

---
*Generated by Q-APRE Framework*
"""
        
        filename = os.path.join(REPORT_DIR, f"{report_id}.md")
        with open(filename, "w", encoding="utf-8") as f:
            f.write(md_content)
        
        print(f"[+] HIP Report generated: {filename}")
        return filename

    @staticmethod
    def get_strategy_name(persona):
        if persona == "script_kiddie": return "Tarpit (Delay)"
        if persona == "recon": return "Misdirection (Fake Assets)"
        if persona == "apt": return "Canary Deception"
        return "Standard Logging"
